# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    labels:
      - '🤖 bot'
      - '📦 dependencies'
    reviewers:
      - 'napster1582'
      - 'JuanRenteM'
      - 'juanmesa2097'
