- label: 'Preview'
  message: 'PR-$prNumber'
  color: 'blue'
  url: 'https://pr-$prNumber.company.com'

- label: 'PR Size'
  message: 'Large'
  color: 'red'
  when: '$additions >= 500'

- label: 'PR Size'
  message: 'Medium'
  color: 'yellow'
  when: '$additions > 200 && $additions < 500'

- label: 'Error'
  message: 'Wrong target branch'
  color: 'red'
  when: "$targetBranchName != 'trunk'"

- message: '$author'
  color: 'green'

- message: 'Work in Progress'
  color: 'yellow'
  when: "$payload.pull_request.title.includes('WIP')"
