version: '3.9'

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: jinen-docs-development
    restart: always
    ports:
      - '3000:80'
    networks:
      - jinen-network
      
  cms:
    build:
      context: .
      dockerfile: Dockerfile.cms
    container_name: jinen-cms-development
    restart: always
    environment:
      JINEN_SERVER_PORT: 3001
      JINEN_SERVER_URL: http://cms:3001
      JINEN_CLIENT_URLS: http://docs:80,http://web:3002
      PAYLOAD_SECRET: my-secret
      PAYLOAD_CONFIG_PATH: dist/payload-config.js
      MONGODB_URI: mongodb://user:root@mongo:27017/?authMechanism=DEFAULT
    ports:
      - '3001:3001'
    networks:
      - jinen-network

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: jinen-web-development
    restart: always
    environment:
      PUBLIC_CMS_URL: http://cms:3001/api
    ports:
      - '3002:3002'
    networks:
      - jinen-network

networks:
  jinen-network:
    external:
      name: jinen-network
