version: '3.9'

services:
    mongo:
        image: mongo:latest
        container_name: jinen-mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: user
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - '27017:27017'
        volumes:
            - mongo_data:/var/lib/mongo/data
        networks:
            - jinen-network               

volumes:
    mongo_data:

networks:
  jinen-network:
    driver: bridge    