name: 🔥 Feature
description: Sugerir una idea para el proyecto
title: '[JINEN-FEATURE] Introduzca un breve resumen de la característica'
labels: ['feature', 'triage']
body:
  - type: checkboxes
    attributes:
      label: ¿Existe algún issue existente para esto?
      description: Por favor, busque en la pestaña de issues para ver si ya existe uno para la característica que está solicitando.
      options:
        - label: He buscado en los issues existentes.
          required: true

  - type: textarea
    id: feature-behavior
    attributes:
      label: Describa el problema que resuelve su solicitud.
      description: Una descripción clara y concisa de cuál es el problema.
      placeholder: Por ejemplo, "Siempre estoy frustrado cuando..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describa la solución que desea.
      render: markdown
      placeholder: Una descripción clara y concisa de lo que desea que suceda.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Contexto adicional
      description: Proporcione cualquier enlace o referencia que nos dé más contexto sobre el problema que está experimentando.
    validations:
      required: false

  - Type: dropdown
    id: contribution
    Attributes:
      Label: ¿Le gustaría realizar un pull-request para esta característica?
      Options:
        - 'Sí 🚀'
        - 'No'
    Validations:
      Required: true
