name: Build and Push Docker Images to Docker Hub

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-stable'
      - 'v*.*.*-alpha'
      - 'v*.*.*-beta'
      - 'v*.*.*-rc.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
