name: Main Workflow

on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-stable'
      - 'v*.*.*-alpha'
      - 'v*.*.*-beta'
      - 'v*.*.*-rc.*'

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml

  release-docs:
    uses: ./.github/workflows/release-docs.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
    needs: [release]

  release-cms:
    uses: ./.github/workflows/release-cms.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
    needs: [release]

  release-web:
    uses: ./.github/workflows/release-web.yaml
    permissions:
      contents: write
      packages: write
      id-token: write
    needs: [release]

  deploy:
    uses: ./.github/workflows/deploy.yaml
    needs: [release-docs, release-cms, release-web]
